sudo: required
services:
  - docker
script: ":"
deploy:
  - provider: script
    script:
      docker build client
    on:
      repo: hugovp/client
  - provider: script
    script:
      docker build api
    on:
      repo: hugovp/api
